FROM turtlebot3sim

ARG LOCAL_USER=turtle

WORKDIR /home/${LOCAL_USER}
RUN sudo apt-get update
RUN sudo apt-get install -y sudo vim doxygen
RUN git clone https://github.com/TaishiUeda/JackOfAllTrades.git && \
    cd JackOfAllTrades/DevEnv && \
    ./install.sh && \
    cd ../../ && sudo rm -r JackOfAllTrades

ENTRYPOINT ["/bin/bash"]

